# Generated by Django 2.1.5 on 2020-06-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('Phone', models.IntegerField()),
                ('Address', models.CharField(max_length=60)),
                ('State', models.CharField(max_length=60)),
                ('zipcode', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Shipped', 'Shipped'), ('UnderProcessing', 'UnderProcessing'), ('Out For delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('Indoor', 'Indoor'), ('OutDoor', 'OutDoor')], max_length=100)),
                ('description', models.CharField(max_length=60)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='Tags',
            field=models.ManyToManyField(to='Management.Tags'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='OrderedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Customer'),
        ),
    ]
