# Generated by Django 2.1.5 on 2020-06-18 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20200617_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
    ]
