# Generated by Django 2.1.5 on 2020-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_customer_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('UnderProcessing', 'UnderProcessing'), ('Out For delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default=0, max_length=60),
        ),
    ]
