# Generated by Django 2.1.5 on 2020-06-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20200622_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
