# Generated by Django 2.1.5 on 2020-06-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_auto_20200625_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
    ]
