# Generated by Django 2.1.5 on 2020-06-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='Profile',
        ),
    ]
