# Generated by Django 2.1.5 on 2020-06-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_auto_20200627_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(default='static/images/Default.jpg', upload_to=''),
        ),
    ]
