# Generated by Django 2.1.5 on 2020-06-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0016_auto_20200628_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(default='Default.jpg', upload_to=''),
        ),
    ]
