# Generated by Django 2.1.5 on 2020-06-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0017_auto_20200628_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(default='Defaut.jpg', upload_to=''),
        ),
    ]
