# Generated by Django 3.0.7 on 2020-07-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0018_auto_20200628_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=360),
        ),
    ]
