# Generated by Django 2.1.5 on 2020-06-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AddField(
            model_name='accounts',
            name='Updated_Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
